apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: go-jzjnptmc
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/go-jzjnptmc:c97b8b727cbeec20c39d63ef44579168d3a69e81@sha256:067e0a009af1fbc809723f53bfd3bd150f0f8298b7d2a10a198f03358a9f53a6
        name: container-image  
